### ISSUE TITLE
HJ Article

### ISSUE THREAD

**Issue by Coxworld** [ChronovaEngineering/Arduino_Clock_Timer#1]
Hello Hazel

I read your joint article with interest and I am debating prototyping your setup to play with.   A few questions ...
Figure 3 pin outs do not match the Arduino code listing - I aim to stick to what the code says.
If I understand correctly the 1pps makes the timing work for a 1s pendulum.   I am not sure how the idea would work with a variable pendulum setup like Microset allows (I own a Microset).
My interest is to use the principle to derive a variable pulse width to an electromagnet to pulse a pendulum as a sustaining force.
This will be on a much modified William Smith Gearless clock design. (https://altrish.co.uk/2020/01/15/silencing-the-bill-smith-gearless-gravity-arm-clock-with-a-new-sustaining-mechanism/).  
My current adaption has two Hall Effect devices that sense mid swing and overswing.  The Arduino counts a preset number of swings and then applies a fixed period pulse.   An overswing condition stops the swing counts until it abates.   It works but I would like something a bit more dynamic.
Kind regards

Alan

**Comment by ChronovaEngineering** [comment]
Hi Alan,

Thanks for reading our article and well spotted! Pins D2 and D3 were assigned the opposite way around in the article block diagram, so I’ve updated them to match here. D2 and D3 are functionally identical, so it doesn’t matter which way around they are, as long as the circuit matches the code.

The current system is optimised for a 1s pendulum but with some adjustments, it should be applicable to any pendulum with a period that is a multiple of 0.5 seconds. The important thing is knowing where the reference PPS pulse should fall relative to the pendulum passing the light gate.

An alternative approach could be counting 59 PPS pulses, then timing the gap between the PPS and the gate pulse on the 60th: i.e. once per minute, as most clocks have an integer number of pendulum swings per minute.

Good luck with your project! I enjoyed reading your blog post about it and others on your site. I hope our timer design is useful to you. Feel free to get in touch if there’s anything you’d like to discuss in more detail.

Best wishes,
Hazel
